language: java

jdk:
  - oraclejdk8

# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

# script for build and release via Travis to Bintray
script:
  - ./gradlew build

after_success:
  - bash <(curl -s https://codecov.io.bash)

notifications:
  email: false

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle